// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAPPCONFIG = "APP_CONFIG"

// APPCONFIG mapped from table <APP_CONFIG>
type APPCONFIG struct {
	NAME        string  `gorm:"column:NAME;type:char;primaryKey" json:"NAME"`
	VALUE       *string `gorm:"column:VALUE;type:nvarchar" json:"VALUE"`
	DATATYPE    *string `gorm:"column:DATATYPE;type:nvarchar" json:"DATATYPE"`
	INTMIN      *int64  `gorm:"column:INT_MIN;type:int" json:"INT_MIN"`
	INTMAX      *int64  `gorm:"column:INT_MAX;type:int" json:"INT_MAX"`
	OPTIONS     *string `gorm:"column:OPTIONS;type:nvarchar" json:"OPTIONS"`
	STRINGREGEX *string `gorm:"column:STRING_REGEX;type:nvarchar" json:"STRING_REGEX"`
}

// TableName APPCONFIG's table name
func (*APPCONFIG) TableName() string {
	return TableNameAPPCONFIG
}
