// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAPPRESPONSECODE = "APP_RESPONSE_CODES"

// APPRESPONSECODE mapped from table <APP_RESPONSE_CODES>
type APPRESPONSECODE struct {
	RESCODE          string  `gorm:"column:RES_CODE;type:varchar;primaryKey" json:"RES_CODE"`
	ERRORCODE        string  `gorm:"column:ERROR_CODE;type:varchar;not null" json:"ERROR_CODE"`
	DESCRIPTION      string  `gorm:"column:DESCRIPTION;type:varchar;not null" json:"DESCRIPTION"`
	DESCRIPTIONLOCAL *string `gorm:"column:DESCRIPTION_LOCAL;type:nvarchar" json:"DESCRIPTION_LOCAL"`
	RESPONSE         string  `gorm:"column:RESPONSE;type:varchar;not null" json:"RESPONSE"`
	RESPONSELOCAL    string  `gorm:"column:RESPONSE_LOCAL;type:nvarchar;not null" json:"RESPONSE_LOCAL"`
	CATEGORY         *int64  `gorm:"column:CATEGORY;type:int" json:"CATEGORY"`
}

// TableName APPRESPONSECODE's table name
func (*APPRESPONSECODE) TableName() string {
	return TableNameAPPRESPONSECODE
}
