// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAPPLOGINSESSION = "APP_LOGIN_SESSIONS"

// APPLOGINSESSION mapped from table <APP_LOGIN_SESSIONS>
type APPLOGINSESSION struct {
	SEQ         int64   `gorm:"column:SEQ;type:int;primaryKey" json:"SEQ"`
	TOKEN       string  `gorm:"column:TOKEN;type:nvarchar;not null" json:"TOKEN"`
	DEVICEID    string  `gorm:"column:DEVICE_ID;type:nvarchar;not null" json:"DEVICE_ID"`
	PLATFORM    string  `gorm:"column:PLATFORM;type:nvarchar;not null" json:"PLATFORM"`
	BROWSER     string  `gorm:"column:BROWSER;type:nvarchar;not null" json:"BROWSER"`
	USERAGENT   string  `gorm:"column:USER_AGENT;type:nvarchar;not null" json:"USER_AGENT"`
	OS          string  `gorm:"column:OS;type:nvarchar;not null" json:"OS"`
	IMEI        string  `gorm:"column:IMEI;type:nvarchar;not null" json:"IMEI"`
	LOGINAT     string  `gorm:"column:LOGIN_AT;type:char;not null" json:"LOGIN_AT"`
	LOGINEXPIRE string  `gorm:"column:LOGIN_EXPIRE;type:char;not null" json:"LOGIN_EXPIRE"`
	LOGINSTATUS *bool   `gorm:"column:LOGIN_STATUS;type:bit;not null;default:1" json:"LOGIN_STATUS"`
	USERID      string  `gorm:"column:USER_ID;type:nvarchar;not null" json:"USER_ID"`
	FCMTOKEN    *string `gorm:"column:FCM_TOKEN;type:nvarchar" json:"FCM_TOKEN"`
}

// TableName APPLOGINSESSION's table name
func (*APPLOGINSESSION) TableName() string {
	return TableNameAPPLOGINSESSION
}
