// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAPPPLATFORMCAT = "APP_PLATFORM_CAT"

// APPPLATFORMCAT mapped from table <APP_PLATFORM_CAT>
type APPPLATFORMCAT struct {
	PLATFORMID   int64  `gorm:"column:PLATFORM_ID;type:int;primaryKey" json:"PLATFORM_ID"`
	PLATFORMNAME string `gorm:"column:PLATFORM_NAME;type:nvarchar;not null;uniqueIndex:WN_PLATFORM_PLATFORM_NAME_key,priority:1" json:"PLATFORM_NAME"`
}

// TableName APPPLATFORMCAT's table name
func (*APPPLATFORMCAT) TableName() string {
	return TableNameAPPPLATFORMCAT
}
