// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCOMMUNICATIONEMAIL = "COMMUNICATION_EMAILS"

// COMMUNICATIONEMAIL mapped from table <COMMUNICATION_EMAILS>
type COMMUNICATIONEMAIL struct {
	SEQ          int64   `gorm:"column:SEQ;type:int;primaryKey" json:"SEQ"`
	EMAILID      string  `gorm:"column:EMAIL_ID;type:nvarchar;not null" json:"EMAIL_ID"`
	EMAILTO      string  `gorm:"column:EMAIL_TO;type:nvarchar;not null" json:"EMAIL_TO"`
	EMAILCC      *string `gorm:"column:EMAIL_CC;type:nvarchar" json:"EMAIL_CC"`
	EMAILBCC     *string `gorm:"column:EMAIL_BCC;type:nvarchar" json:"EMAIL_BCC"`
	EMAILSUBJECT string  `gorm:"column:EMAIL_SUBJECT;type:nvarchar;not null" json:"EMAIL_SUBJECT"`
	EMAILBODY    string  `gorm:"column:EMAIL_BODY;type:nvarchar;not null" json:"EMAIL_BODY"`
	EMAILSTATUS  *bool   `gorm:"column:EMAIL_STATUS;type:bit;not null;default:0" json:"EMAIL_STATUS"`
	EMAILAT      string  `gorm:"column:EMAIL_AT;type:char;not null" json:"EMAIL_AT"`
	EMAILEXPIRE  string  `gorm:"column:EMAIL_EXPIRE;type:char;not null" json:"EMAIL_EXPIRE"`
	EMAILTYPE    string  `gorm:"column:EMAIL_TYPE;type:nvarchar;not null" json:"EMAIL_TYPE"`
	CREATEDBY    string  `gorm:"column:CREATED_BY;type:nvarchar;not null" json:"CREATED_BY"`
	UPDATEDBY    *string `gorm:"column:UPDATED_BY;type:nvarchar" json:"UPDATED_BY"`
	CREATEDAT    string  `gorm:"column:CREATED_AT;type:char;not null" json:"CREATED_AT"`
	UPDATEDAT    *string `gorm:"column:UPDATED_AT;type:char" json:"UPDATED_AT"`
}

// TableName COMMUNICATIONEMAIL's table name
func (*COMMUNICATIONEMAIL) TableName() string {
	return TableNameCOMMUNICATIONEMAIL
}
