// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameORGROOMSCAT = "ORG_ROOMS_CAT"

// ORGROOMSCAT mapped from table <ORG_ROOMS_CAT>
type ORGROOMSCAT struct {
	ROOMCATSEQ      int64  `gorm:"column:ROOM_CAT_SEQ;type:int;primaryKey" json:"ROOM_CAT_SEQ"`
	ROOMCATNAME     string `gorm:"column:ROOM_CAT_NAME;type:nvarchar;not null" json:"ROOM_CAT_NAME"`
	ROOMCATCAPACITY int64  `gorm:"column:ROOM_CAT_CAPACITY;type:int;not null" json:"ROOM_CAT_CAPACITY"`
}

// TableName ORGROOMSCAT's table name
func (*ORGROOMSCAT) TableName() string {
	return TableNameORGROOMSCAT
}
