// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameORGOFFICE = "ORG_OFFICES"

// ORGOFFICE mapped from table <ORG_OFFICES>
type ORGOFFICE struct {
	OFFICEUNQCD   string  `gorm:"column:OFFICE_UNQCD;type:nvarchar;primaryKey" json:"OFFICE_UNQCD"`
	OFFICENAME    string  `gorm:"column:OFFICE_NAME;type:nvarchar;not null;index:IDX_OFFICE_NAME,priority:1" json:"OFFICE_NAME"`
	OFFICEADDRESS *string `gorm:"column:OFFICE_ADDRESS;type:nvarchar" json:"OFFICE_ADDRESS"`
	COMPANYCODE   string  `gorm:"column:COMPANY_CODE;type:char;not null" json:"COMPANY_CODE"`
	ISACTIVE      *bool   `gorm:"column:IS_ACTIVE;type:bit;not null;default:1" json:"IS_ACTIVE"`
}

// TableName ORGOFFICE's table name
func (*ORGOFFICE) TableName() string {
	return TableNameORGOFFICE
}
