// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameORGDEPTCODE = "ORG_DEPT_CODE"

// ORGDEPTCODE mapped from table <ORG_DEPT_CODE>
type ORGDEPTCODE struct {
	DEPTSEQ  int64  `gorm:"column:DEPT_SEQ;type:int;primaryKey" json:"DEPT_SEQ"`
	DEPTCODE string `gorm:"column:DEPT_CODE;type:nvarchar;not null;index:IDX_DT_CODE,priority:1" json:"DEPT_CODE"`
	DEPTNAME string `gorm:"column:DEPT_NAME;type:nvarchar;not null" json:"DEPT_NAME"`
}

// TableName ORGDEPTCODE's table name
func (*ORGDEPTCODE) TableName() string {
	return TableNameORGDEPTCODE
}
