// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameORGDAILYTIME = "ORG_DAILY_TIME"

// ORGDAILYTIME mapped from table <ORG_DAILY_TIME>
type ORGDAILYTIME struct {
	LOCATION       string  `gorm:"column:LOCATION;type:nvarchar;primaryKey" json:"LOCATION"`
	LOCATIONID     int64   `gorm:"column:LOCATION_ID;type:int;primaryKey" json:"LOCATION_ID"`
	TIMETYPE       string  `gorm:"column:TIME_TYPE;type:char;not null" json:"TIME_TYPE"`
	ALWAYSOPEN     string  `gorm:"column:ALWAYS_OPEN;type:char;not null" json:"ALWAYS_OPEN"`
	ALWAYSCLOSE    string  `gorm:"column:ALWAYS_CLOSE;type:char;not null" json:"ALWAYS_CLOSE"`
	SUNDAY         *bool   `gorm:"column:SUNDAY;type:bit;not null;default:0" json:"SUNDAY"`
	SUNDAYOPEN     *string `gorm:"column:SUNDAY_OPEN;type:char" json:"SUNDAY_OPEN"`
	SUNDAYCLOSE    *string `gorm:"column:SUNDAY_CLOSE;type:char" json:"SUNDAY_CLOSE"`
	MONDAY         *bool   `gorm:"column:MONDAY;type:bit;not null;default:0" json:"MONDAY"`
	MONDAYOPEN     *string `gorm:"column:MONDAY_OPEN;type:char" json:"MONDAY_OPEN"`
	MONDAYCLOSE    *string `gorm:"column:MONDAY_CLOSE;type:char" json:"MONDAY_CLOSE"`
	TUESDAY        *bool   `gorm:"column:TUESDAY;type:bit;not null;default:0" json:"TUESDAY"`
	TUESDAYOPEN    *string `gorm:"column:TUESDAY_OPEN;type:char" json:"TUESDAY_OPEN"`
	TUESDAYCLOSE   *string `gorm:"column:TUESDAY_CLOSE;type:char" json:"TUESDAY_CLOSE"`
	WEDNESDAY      *bool   `gorm:"column:WEDNESDAY;type:bit;not null;default:0" json:"WEDNESDAY"`
	WEDNESDAYOPEN  *string `gorm:"column:WEDNESDAY_OPEN;type:char" json:"WEDNESDAY_OPEN"`
	WEDNESDAYCLOSE *string `gorm:"column:WEDNESDAY_CLOSE;type:char" json:"WEDNESDAY_CLOSE"`
	THURSDAY       *bool   `gorm:"column:THURSDAY;type:bit;not null;default:0" json:"THURSDAY"`
	THURSDAYOPEN   *string `gorm:"column:THURSDAY_OPEN;type:char" json:"THURSDAY_OPEN"`
	THURSDAYCLOSE  *string `gorm:"column:THURSDAY_CLOSE;type:char" json:"THURSDAY_CLOSE"`
	FRIDAY         *bool   `gorm:"column:FRIDAY;type:bit;not null;default:0" json:"FRIDAY"`
	FRIDAYOPEN     *string `gorm:"column:FRIDAY_OPEN;type:char" json:"FRIDAY_OPEN"`
	FRIDAYCLOSE    *string `gorm:"column:FRIDAY_CLOSE;type:char" json:"FRIDAY_CLOSE"`
	SATURDAY       *bool   `gorm:"column:SATURDAY;type:bit;not null;default:0" json:"SATURDAY"`
	SATURDAYOPEN   *string `gorm:"column:SATURDAY_OPEN;type:char" json:"SATURDAY_OPEN"`
	SATURDAYCLOSE  *string `gorm:"column:SATURDAY_CLOSE;type:char" json:"SATURDAY_CLOSE"`
}

// TableName ORGDAILYTIME's table name
func (*ORGDAILYTIME) TableName() string {
	return TableNameORGDAILYTIME
}
