// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameORGHOLIDAY = "ORG_HOLIDAY"

// ORGHOLIDAY mapped from table <ORG_HOLIDAY>
type ORGHOLIDAY struct {
	HOLIDAYID      int64   `gorm:"column:HOLIDAY_ID;type:int;primaryKey" json:"HOLIDAY_ID"`
	HOLIDAYDATE    string  `gorm:"column:HOLIDAY_DATE;type:char;not null" json:"HOLIDAY_DATE"`
	HOLIDAYNAME    string  `gorm:"column:HOLIDAY_NAME;type:nvarchar;not null" json:"HOLIDAY_NAME"`
	HOLIDAYREASON  *string `gorm:"column:HOLIDAY_REASON;type:nvarchar" json:"HOLIDAY_REASON"`
	COMPANYHOLIDAY *bool   `gorm:"column:COMPANY_HOLIDAY;type:bit;not null;default:0" json:"COMPANY_HOLIDAY"`
	OFFICEID       int64   `gorm:"column:OFFICE_ID;type:int;not null" json:"OFFICE_ID"`
}

// TableName ORGHOLIDAY's table name
func (*ORGHOLIDAY) TableName() string {
	return TableNameORGHOLIDAY
}
