// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameORGFLOOR = "ORG_FLOORS"

// ORGFLOOR mapped from table <ORG_FLOORS>
type ORGFLOOR struct {
	FLOORSEQ    int64  `gorm:"column:FLOOR_SEQ;type:int;primaryKey" json:"FLOOR_SEQ"`
	FLOORNAME   string `gorm:"column:FLOOR_NAME;type:nvarchar;not null;index:IDX_FLOOR_NAME,priority:1" json:"FLOOR_NAME"`
	OFFICEUNQCD string `gorm:"column:OFFICE_UNQCD;type:nvarchar;not null" json:"OFFICE_UNQCD"`
	ISACTIVE    *bool  `gorm:"column:IS_ACTIVE;type:bit;not null;default:1" json:"IS_ACTIVE"`
}

// TableName ORGFLOOR's table name
func (*ORGFLOOR) TableName() string {
	return TableNameORGFLOOR
}
