// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameORGIDENTITYCODE = "ORG_IDENTITY_CODE"

// ORGIDENTITYCODE mapped from table <ORG_IDENTITY_CODE>
type ORGIDENTITYCODE struct {
	IDNTYSEQ int64  `gorm:"column:IDNTY_SEQ;type:int;primaryKey" json:"IDNTY_SEQ"`
	IDNTCODE string `gorm:"column:IDNT_CODE;type:nvarchar;not null;index:IDX_DT_CODE,priority:1" json:"IDNT_CODE"`
	IDNTNAME string `gorm:"column:IDNT_NAME;type:nvarchar;not null" json:"IDNT_NAME"`
}

// TableName ORGIDENTITYCODE's table name
func (*ORGIDENTITYCODE) TableName() string {
	return TableNameORGIDENTITYCODE
}
