// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameORGROOM = "ORG_ROOMS"

// ORGROOM mapped from table <ORG_ROOMS>
type ORGROOM struct {
	ROOMID       int64  `gorm:"column:ROOM_ID;type:int;primaryKey" json:"ROOM_ID"`
	ROOMNUMBER   int64  `gorm:"column:ROOM_NUMBER;type:int;not null" json:"ROOM_NUMBER"`
	ROOMNAME     string `gorm:"column:ROOM_NAME;type:nvarchar;not null;index:IDX_ROOM_NAME,priority:1;index:IDX_ROOM_NAME_FLOOR_ID,priority:1" json:"ROOM_NAME"`
	FLOORSEQ     int64  `gorm:"column:FLOOR_SEQ;type:int;not null;index:IDX_ROOM_NAME_FLOOR_ID,priority:2" json:"FLOOR_SEQ"`
	ROOMCATSEQ   *int64 `gorm:"column:ROOM_CAT_SEQ;type:int" json:"ROOM_CAT_SEQ"`
	ROOMCAPACITY int64  `gorm:"column:ROOM_CAPACITY;type:int;not null" json:"ROOM_CAPACITY"`
	ISACTIVE     *bool  `gorm:"column:IS_ACTIVE;type:bit;not null;default:1" json:"IS_ACTIVE"`
}

// TableName ORGROOM's table name
func (*ORGROOM) TableName() string {
	return TableNameORGROOM
}
