// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameORGROLECODE = "ORG_ROLE_CODE"

// ORGROLECODE mapped from table <ORG_ROLE_CODE>
type ORGROLECODE struct {
	ROLESEQ  int64  `gorm:"column:ROLE_SEQ;type:int;primaryKey" json:"ROLE_SEQ"`
	ROLECODE string `gorm:"column:ROLE_CODE;type:char;not null;index:IDX_ROLE_CODE,priority:1" json:"ROLE_CODE"`
	ROLENAME string `gorm:"column:ROLE_NAME;type:nvarchar;not null" json:"ROLE_NAME"`
}

// TableName ORGROLECODE's table name
func (*ORGROLECODE) TableName() string {
	return TableNameORGROLECODE
}
