// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePANTRYORDER = "PANTRY_ORDERS"

// PANTRYORDER mapped from table <PANTRY_ORDERS>
type PANTRYORDER struct {
	ORDERID        string  `gorm:"column:ORDER_ID;type:nvarchar;primaryKey" json:"ORDER_ID"`
	BOOKINGID      string  `gorm:"column:BOOKING_ID;type:nvarchar;not null;index:IDX_BOOKING_ROOM_PANTRY_HOST_ORDER_DATETIME,priority:1" json:"BOOKING_ID"`
	PANTRYID       int64   `gorm:"column:PANTRY_ID;type:int;not null;index:IDX_BOOKING_ROOM_PANTRY_HOST_ORDER_DATETIME,priority:3;index:IDX_PANTRY_ORDER_DATETIME,priority:1" json:"PANTRY_ID"`
	PANTRYCODE     string  `gorm:"column:PANTRY_CODE;type:nvarchar;not null" json:"PANTRY_CODE"`
	ROOMID         int64   `gorm:"column:ROOM_ID;type:int;not null;index:IDX_BOOKING_ROOM_PANTRY_HOST_ORDER_DATETIME,priority:2;index:IDX_ROOM_ORDER_DATETIME,priority:1" json:"ROOM_ID"`
	HOSTID         string  `gorm:"column:HOST_ID;type:nvarchar;not null;index:IDX_BOOKING_ROOM_PANTRY_HOST_ORDER_DATETIME,priority:4;index:IDX_HOST_ORDER_DATETIME,priority:1" json:"HOST_ID"`
	HOSTNAME       string  `gorm:"column:HOST_NAME;type:nvarchar;not null" json:"HOST_NAME"`
	ORDERDATETIME  string  `gorm:"column:ORDER_DATETIME;type:char;not null;index:IDX_BOOKING_ROOM_PANTRY_HOST_ORDER_DATETIME,priority:5;index:IDX_HOST_ORDER_DATETIME,priority:2;index:IDX_PANTRY_ORDER_DATETIME,priority:2;index:IDX_ROOM_ORDER_DATETIME,priority:2" json:"ORDER_DATETIME"`
	STATUS         int64   `gorm:"column:STATUS;type:int;not null" json:"STATUS"`
	ORDERCONFIRMAT *string `gorm:"column:ORDER_CONFIRM_AT;type:char" json:"ORDER_CONFIRM_AT"`
	ORDERDELIVERAT *string `gorm:"column:ORDER_DELIVER_AT;type:char" json:"ORDER_DELIVER_AT"`
	ORDERCANCELAT  *string `gorm:"column:ORDER_CANCEL_AT;type:char" json:"ORDER_CANCEL_AT"`
	PROCESSEDBY    *string `gorm:"column:PROCESSED_BY;type:nvarchar" json:"PROCESSED_BY"`
}

// TableName PANTRYORDER's table name
func (*PANTRYORDER) TableName() string {
	return TableNamePANTRYORDER
}
