// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePANTRYLIST = "PANTRY_LIST"

// PANTRYLIST mapped from table <PANTRY_LIST>
type PANTRYLIST struct {
	PANTRYID    int64  `gorm:"column:PANTRY_ID;type:int;primaryKey" json:"PANTRY_ID"`
	PANTRYUNQCD string `gorm:"column:PANTRY_UNQCD;type:nvarchar;not null;uniqueIndex:WN_PANTRY_PANTRY_UNQCD_key,priority:1;index:IDX_PANTRY_UNQCD,priority:1" json:"PANTRY_UNQCD"`
	PANTRYCODE  string `gorm:"column:PANTRY_CODE;type:nvarchar;not null;uniqueIndex:WN_PANTRY_PANTRY_CODE_key,priority:1;index:IDX_PANTRY_CODE,priority:1" json:"PANTRY_CODE"`
	PANTRYNAME  string `gorm:"column:PANTRY_NAME;type:nvarchar;not null;index:IDX_PANTRY_NAME,priority:1" json:"PANTRY_NAME"`
}

// TableName PANTRYLIST's table name
func (*PANTRYLIST) TableName() string {
	return TableNamePANTRYLIST
}
