// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePANTRYITEMSCAT = "PANTRY_ITEMS_CAT"

// PANTRYITEMSCAT mapped from table <PANTRY_ITEMS_CAT>
type PANTRYITEMSCAT struct {
	CATSEQ    int64  `gorm:"column:CAT_SEQ;type:int;primaryKey" json:"CAT_SEQ"`
	CATNAME   string `gorm:"column:CAT_NAME;type:nvarchar;not null;uniqueIndex:WN_PANTRY_ITEMS_CATEGORY_CAT_NAME_key,priority:1;index:IDX_CAT_NAME,priority:1" json:"CAT_NAME"`
	CATACTIVE *bool  `gorm:"column:CAT_ACTIVE;type:bit;not null;default:1" json:"CAT_ACTIVE"`
}

// TableName PANTRYITEMSCAT's table name
func (*PANTRYITEMSCAT) TableName() string {
	return TableNamePANTRYITEMSCAT
}
