// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePANTRYITEM = "PANTRY_ITEMS"

// PANTRYITEM mapped from table <PANTRY_ITEMS>
type PANTRYITEM struct {
	SEQ      int64  `gorm:"column:SEQ;type:int;primaryKey" json:"SEQ"`
	ITEMCODE string `gorm:"column:ITEM_CODE;type:nvarchar;not null;uniqueIndex:WN_PANTRY_ITEMS_ITEM_CODE_key,priority:1;index:IDX_ITEM_CODE,priority:1" json:"ITEM_CODE"`
	ITEMICON string `gorm:"column:ITEM_ICON;type:nvarchar;not null" json:"ITEM_ICON"`
	ITEMNAME string `gorm:"column:ITEM_NAME;type:nvarchar;not null;index:IDX_ITEM_NAME,priority:1" json:"ITEM_NAME"`
	CATSEQ   int64  `gorm:"column:CAT_SEQ;type:int;not null" json:"CAT_SEQ"`
}

// TableName PANTRYITEM's table name
func (*PANTRYITEM) TableName() string {
	return TableNamePANTRYITEM
}
