// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePANTRYROOMPANTRYMAPPING = "PANTRY_ROOM_PANTRY_MAPPING"

// PANTRYROOMPANTRYMAPPING mapped from table <PANTRY_ROOM_PANTRY_MAPPING>
type PANTRYROOMPANTRYMAPPING struct {
	PANTRYID int64 `gorm:"column:PANTRY_ID;type:int;primaryKey;index:IDX_PANTRY_ROOMS_MAPPING,priority:1" json:"PANTRY_ID"`
	ROOMSID  int64 `gorm:"column:ROOMS_ID;type:int;primaryKey;index:IDX_PANTRY_ROOMS_MAPPING,priority:2" json:"ROOMS_ID"`
	ISACTIVE *bool `gorm:"column:IS_ACTIVE;type:bit;not null;default:1" json:"IS_ACTIVE"`
}

// TableName PANTRYROOMPANTRYMAPPING's table name
func (*PANTRYROOMPANTRYMAPPING) TableName() string {
	return TableNamePANTRYROOMPANTRYMAPPING
}
