// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePANTRYITEMUNIT = "PANTRY_ITEMUNITS"

// PANTRYITEMUNIT mapped from table <PANTRY_ITEMUNITS>
type PANTRYITEMUNIT struct {
	UNITID   int64  `gorm:"column:UNIT_ID;type:int;primaryKey" json:"UNIT_ID"`
	UNITNAME string `gorm:"column:UNIT_NAME;type:nvarchar;not null;uniqueIndex:WN_UNIT_OF_ITEM_UNIT_NAME_key,priority:1;index:IDX_UNIT_NAME,priority:1" json:"UNIT_NAME"`
	UNITCODE string `gorm:"column:UNIT_CODE;type:nvarchar;not null;uniqueIndex:WN_UNIT_OF_ITEM_UNIT_CODE_key,priority:1" json:"UNIT_CODE"`
}

// TableName PANTRYITEMUNIT's table name
func (*PANTRYITEMUNIT) TableName() string {
	return TableNamePANTRYITEMUNIT
}
