// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePANTRYORDERSITEM = "PANTRY_ORDERS_ITEMS"

// PANTRYORDERSITEM mapped from table <PANTRY_ORDERS_ITEMS>
type PANTRYORDERSITEM struct {
	ORDERID         string  `gorm:"column:ORDER_ID;type:nvarchar;primaryKey;index:IDX_ORDER_ITEM,priority:1" json:"ORDER_ID"`
	ITEMID          int64   `gorm:"column:ITEM_ID;type:int;not null;index:IDX_ORDER_ITEM,priority:2" json:"ITEM_ID"`
	ITEMCODE        string  `gorm:"column:ITEM_CODE;type:nvarchar;not null" json:"ITEM_CODE"`
	QTY             int64   `gorm:"column:QTY;type:int;not null" json:"QTY"`
	ORDERITEMSTATUS int64   `gorm:"column:ORDER_ITEM_STATUS;type:int;not null" json:"ORDER_ITEM_STATUS"`
	COMMENT         *string `gorm:"column:COMMENT;type:nvarchar" json:"COMMENT"`
}

// TableName PANTRYORDERSITEM's table name
func (*PANTRYORDERSITEM) TableName() string {
	return TableNamePANTRYORDERSITEM
}
