// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePANTRYINVENTORYREGISTER = "PANTRY_INVENTORY_REGISTER"

// PANTRYINVENTORYREGISTER mapped from table <PANTRY_INVENTORY_REGISTER>
type PANTRYINVENTORYREGISTER struct {
	SEQID             int64   `gorm:"column:SEQ_ID;type:int;primaryKey" json:"SEQ_ID"`
	INVENTORYDATETIME string  `gorm:"column:INVENTORY_DATE_TIME;type:char;not null;index:IDX_INVENTORY_DATE_TIME,priority:1;index:IDX_PANTRY_INVENTORY_DATE_TIME,priority:2" json:"INVENTORY_DATE_TIME"`
	ITEMID            int64   `gorm:"column:ITEM_ID;type:int;not null;index:IDX_INVENTORY_DATE_TIME,priority:2" json:"ITEM_ID"`
	ITEMNAME          string  `gorm:"column:ITEM_NAME;type:nvarchar;not null" json:"ITEM_NAME"`
	OPENINGQTY        float64 `gorm:"column:OPENING_QTY;type:float;not null" json:"OPENING_QTY"`
	SPENTQTY          float64 `gorm:"column:SPENT_QTY;type:float;not null" json:"SPENT_QTY"`
	TOTALQTY          float64 `gorm:"column:TOTAL_QTY;type:float;not null" json:"TOTAL_QTY"`
	MINIMUMQTYSET     float64 `gorm:"column:MINIMUM_QTY_SET;type:float;not null" json:"MINIMUM_QTY_SET"`
	UNITID            int64   `gorm:"column:UNIT_ID;type:int;not null" json:"UNIT_ID"`
	UNITNAME          string  `gorm:"column:UNIT_NAME;type:nvarchar;not null" json:"UNIT_NAME"`
	PANTRYID          int64   `gorm:"column:PANTRY_ID;type:int;not null;index:IDX_PANTRY_INVENTORY_DATE_TIME,priority:1" json:"PANTRY_ID"`
}

// TableName PANTRYINVENTORYREGISTER's table name
func (*PANTRYINVENTORYREGISTER) TableName() string {
	return TableNamePANTRYINVENTORYREGISTER
}
