// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVMSAMENITY = "VMS_AMENITIES"

// VMSAMENITY mapped from table <VMS_AMENITIES>
type VMSAMENITY struct {
	AMENITIESID   int64   `gorm:"column:AMENITIES_ID;type:int;primaryKey" json:"AMENITIES_ID"`
	AMENITIESNAME string  `gorm:"column:AMENITIES_NAME;type:nvarchar;not null;index:IDX_AMENITIES_NAME,priority:1" json:"AMENITIES_NAME"`
	ICON          *string `gorm:"column:ICON;type:nvarchar" json:"ICON"`
	ISACTIVE      *bool   `gorm:"column:IS_ACTIVE;type:bit;not null;default:1" json:"IS_ACTIVE"`
	CREATEDAT     string  `gorm:"column:CREATED_AT;type:char;not null" json:"CREATED_AT"`
	UPDATEDAT     *string `gorm:"column:UPDATED_AT;type:char" json:"UPDATED_AT"`
}

// TableName VMSAMENITY's table name
func (*VMSAMENITY) TableName() string {
	return TableNameVMSAMENITY
}
