// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVMSROOMAMENITIESMAP = "VMS_ROOM_AMENITIES_MAP"

// VMSROOMAMENITIESMAP mapped from table <VMS_ROOM_AMENITIES_MAP>
type VMSROOMAMENITIESMAP struct {
	ROOMID      int64 `gorm:"column:ROOM_ID;type:int;primaryKey;index:IDX_ROOM_AMENITIES_MAPPING,priority:1" json:"ROOM_ID"`
	AMENITIESID int64 `gorm:"column:AMENITIES_ID;type:int;primaryKey;index:IDX_ROOM_AMENITIES_MAPPING,priority:2" json:"AMENITIES_ID"`
}

// TableName VMSROOMAMENITIESMAP's table name
func (*VMSROOMAMENITIESMAP) TableName() string {
	return TableNameVMSROOMAMENITIESMAP
}
