// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVMSBOOKING = "VMS_BOOKINGS"

// VMSBOOKING mapped from table <VMS_BOOKINGS>
type VMSBOOKING struct {
	BOOKINGID            string  `gorm:"column:BOOKING_ID;type:nvarchar;primaryKey" json:"BOOKING_ID"`
	ROOMID               int64   `gorm:"column:ROOM_ID;type:int;not null;index:IDX_ROOM_BOOKING_DATE_TIME,priority:1;index:IDX_ROOM_FLOOR_OFFICE_BOOKING_DATE_TIME,priority:1" json:"ROOM_ID"`
	ROOMNO               string  `gorm:"column:ROOM_NO;type:nvarchar;not null" json:"ROOM_NO"`
	FLOORID              int64   `gorm:"column:FLOOR_ID;type:int;not null;index:IDX_ROOM_FLOOR_OFFICE_BOOKING_DATE_TIME,priority:2" json:"FLOOR_ID"`
	FLOORNO              string  `gorm:"column:FLOOR_NO;type:nvarchar;not null" json:"FLOOR_NO"`
	OFFICEID             int64   `gorm:"column:OFFICE_ID;type:int;not null;index:IDX_ROOM_FLOOR_OFFICE_BOOKING_DATE_TIME,priority:3" json:"OFFICE_ID"`
	OFFICENAME           string  `gorm:"column:OFFICE_NAME;type:nvarchar;not null" json:"OFFICE_NAME"`
	USERID               string  `gorm:"column:USER_ID;type:nvarchar;not null;index:IDX_USER_BOOKING_DATE_TIME,priority:1" json:"USER_ID"`
	USERNAME             string  `gorm:"column:USER_NAME;type:nvarchar;not null" json:"USER_NAME"`
	USERIDENTITYCODE     *string `gorm:"column:USER_IDENTITY_CODE;type:char" json:"USER_IDENTITY_CODE"`
	USERDEPARTMENTCODE   *string `gorm:"column:USER_DEPARTMENT_CODE;type:char" json:"USER_DEPARTMENT_CODE"`
	USERTYPE             string  `gorm:"column:USER_TYPE;type:char;not null" json:"USER_TYPE"`
	BOOKINGMODE          string  `gorm:"column:BOOKING_MODE;type:char;not null" json:"BOOKING_MODE"`
	DEVICEID             *string `gorm:"column:DEVICE_ID;type:nvarchar" json:"DEVICE_ID"`
	STATUS               string  `gorm:"column:STATUS;type:char;not null" json:"STATUS"`
	CONFIRMATIONDATETIME *string `gorm:"column:CONFIRMATION_DATE_TIME;type:char" json:"CONFIRMATION_DATE_TIME"`
	CANCELLATIONDATETIME *string `gorm:"column:CANCELLATION_DATE_TIME;type:char" json:"CANCELLATION_DATE_TIME"`
	RETURNDATETIME       *string `gorm:"column:RETURN_DATE_TIME;type:char" json:"RETURN_DATE_TIME"`
	COMPLETEDATETIME     *string `gorm:"column:COMPLETE_DATE_TIME;type:char" json:"COMPLETE_DATE_TIME"`
	BOOKINGSTARTDATETIME string  `gorm:"column:BOOKING_START_DATE_TIME;type:char;not null;index:IDX_BOOKING_DATE_TIME,priority:1;index:IDX_ROOM_BOOKING_DATE_TIME,priority:2;index:IDX_ROOM_FLOOR_OFFICE_BOOKING_DATE_TIME,priority:4;index:IDX_USER_BOOKING_DATE_TIME,priority:2" json:"BOOKING_START_DATE_TIME"`
	BOOKINGENDDATETIME   string  `gorm:"column:BOOKING_END_DATE_TIME;type:char;not null;index:IDX_BOOKING_DATE_TIME,priority:2;index:IDX_ROOM_BOOKING_DATE_TIME,priority:3;index:IDX_ROOM_FLOOR_OFFICE_BOOKING_DATE_TIME,priority:5;index:IDX_USER_BOOKING_DATE_TIME,priority:3" json:"BOOKING_END_DATE_TIME"`
	BOOKINGDATETIME      string  `gorm:"column:BOOKING_DATE_TIME;type:char;not null" json:"BOOKING_DATE_TIME"`
}

// TableName VMSBOOKING's table name
func (*VMSBOOKING) TableName() string {
	return TableNameVMSBOOKING
}
