// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVMSBOOKINGSMEMBER = "VMS_BOOKINGS_MEMBERS"

// VMSBOOKINGSMEMBER mapped from table <VMS_BOOKINGS_MEMBERS>
type VMSBOOKINGSMEMBER struct {
	BOOKINGID          string  `gorm:"column:BOOKING_ID;type:nvarchar;primaryKey" json:"BOOKING_ID"`
	USERID             string  `gorm:"column:USER_ID;type:nvarchar;not null;index:IDX_USER_ID,priority:1" json:"USER_ID"`
	USERNAME           string  `gorm:"column:USER_NAME;type:nvarchar;not null;index:IDX_USER_NAME,priority:1" json:"USER_NAME"`
	USERIDENTITYCODE   *string `gorm:"column:USER_IDENTITY_CODE;type:char;index:IDX_USER_DEPARTMENT_CODE_IDENTITY_CODE,priority:2" json:"USER_IDENTITY_CODE"`
	USERDEPARTMENTCODE *string `gorm:"column:USER_DEPARTMENT_CODE;type:char;index:IDX_USER_DEPARTMENT_CODE_IDENTITY_CODE,priority:1" json:"USER_DEPARTMENT_CODE"`
	USERTYPE           string  `gorm:"column:USER_TYPE;type:char;not null" json:"USER_TYPE"`
	ISHOST             *bool   `gorm:"column:IS_HOST;type:bit;not null;default:0" json:"IS_HOST"`
}

// TableName VMSBOOKINGSMEMBER's table name
func (*VMSBOOKINGSMEMBER) TableName() string {
	return TableNameVMSBOOKINGSMEMBER
}
