// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"SMART_OFFICE_APP/pkg/db/model"
)

func newPANTRYITEMUNIT(db *gorm.DB, opts ...gen.DOOption) pANTRYITEMUNIT {
	_pANTRYITEMUNIT := pANTRYITEMUNIT{}

	_pANTRYITEMUNIT.pANTRYITEMUNITDo.UseDB(db, opts...)
	_pANTRYITEMUNIT.pANTRYITEMUNITDo.UseModel(&model.PANTRYITEMUNIT{})

	tableName := _pANTRYITEMUNIT.pANTRYITEMUNITDo.TableName()
	_pANTRYITEMUNIT.ALL = field.NewAsterisk(tableName)
	_pANTRYITEMUNIT.UNITID = field.NewInt64(tableName, "UNIT_ID")
	_pANTRYITEMUNIT.UNITNAME = field.NewString(tableName, "UNIT_NAME")
	_pANTRYITEMUNIT.UNITCODE = field.NewString(tableName, "UNIT_CODE")

	_pANTRYITEMUNIT.fillFieldMap()

	return _pANTRYITEMUNIT
}

type pANTRYITEMUNIT struct {
	pANTRYITEMUNITDo

	ALL      field.Asterisk
	UNITID   field.Int64
	UNITNAME field.String
	UNITCODE field.String

	fieldMap map[string]field.Expr
}

func (p pANTRYITEMUNIT) Table(newTableName string) *pANTRYITEMUNIT {
	p.pANTRYITEMUNITDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p pANTRYITEMUNIT) As(alias string) *pANTRYITEMUNIT {
	p.pANTRYITEMUNITDo.DO = *(p.pANTRYITEMUNITDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *pANTRYITEMUNIT) updateTableName(table string) *pANTRYITEMUNIT {
	p.ALL = field.NewAsterisk(table)
	p.UNITID = field.NewInt64(table, "UNIT_ID")
	p.UNITNAME = field.NewString(table, "UNIT_NAME")
	p.UNITCODE = field.NewString(table, "UNIT_CODE")

	p.fillFieldMap()

	return p
}

func (p *pANTRYITEMUNIT) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *pANTRYITEMUNIT) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 3)
	p.fieldMap["UNIT_ID"] = p.UNITID
	p.fieldMap["UNIT_NAME"] = p.UNITNAME
	p.fieldMap["UNIT_CODE"] = p.UNITCODE
}

func (p pANTRYITEMUNIT) clone(db *gorm.DB) pANTRYITEMUNIT {
	p.pANTRYITEMUNITDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p pANTRYITEMUNIT) replaceDB(db *gorm.DB) pANTRYITEMUNIT {
	p.pANTRYITEMUNITDo.ReplaceDB(db)
	return p
}

type pANTRYITEMUNITDo struct{ gen.DO }

func (p pANTRYITEMUNITDo) Debug() *pANTRYITEMUNITDo {
	return p.withDO(p.DO.Debug())
}

func (p pANTRYITEMUNITDo) WithContext(ctx context.Context) *pANTRYITEMUNITDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p pANTRYITEMUNITDo) ReadDB() *pANTRYITEMUNITDo {
	return p.Clauses(dbresolver.Read)
}

func (p pANTRYITEMUNITDo) WriteDB() *pANTRYITEMUNITDo {
	return p.Clauses(dbresolver.Write)
}

func (p pANTRYITEMUNITDo) Session(config *gorm.Session) *pANTRYITEMUNITDo {
	return p.withDO(p.DO.Session(config))
}

func (p pANTRYITEMUNITDo) Clauses(conds ...clause.Expression) *pANTRYITEMUNITDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p pANTRYITEMUNITDo) Returning(value interface{}, columns ...string) *pANTRYITEMUNITDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p pANTRYITEMUNITDo) Not(conds ...gen.Condition) *pANTRYITEMUNITDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p pANTRYITEMUNITDo) Or(conds ...gen.Condition) *pANTRYITEMUNITDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p pANTRYITEMUNITDo) Select(conds ...field.Expr) *pANTRYITEMUNITDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p pANTRYITEMUNITDo) Where(conds ...gen.Condition) *pANTRYITEMUNITDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p pANTRYITEMUNITDo) Order(conds ...field.Expr) *pANTRYITEMUNITDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p pANTRYITEMUNITDo) Distinct(cols ...field.Expr) *pANTRYITEMUNITDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p pANTRYITEMUNITDo) Omit(cols ...field.Expr) *pANTRYITEMUNITDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p pANTRYITEMUNITDo) Join(table schema.Tabler, on ...field.Expr) *pANTRYITEMUNITDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p pANTRYITEMUNITDo) LeftJoin(table schema.Tabler, on ...field.Expr) *pANTRYITEMUNITDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p pANTRYITEMUNITDo) RightJoin(table schema.Tabler, on ...field.Expr) *pANTRYITEMUNITDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p pANTRYITEMUNITDo) Group(cols ...field.Expr) *pANTRYITEMUNITDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p pANTRYITEMUNITDo) Having(conds ...gen.Condition) *pANTRYITEMUNITDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p pANTRYITEMUNITDo) Limit(limit int) *pANTRYITEMUNITDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p pANTRYITEMUNITDo) Offset(offset int) *pANTRYITEMUNITDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p pANTRYITEMUNITDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *pANTRYITEMUNITDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p pANTRYITEMUNITDo) Unscoped() *pANTRYITEMUNITDo {
	return p.withDO(p.DO.Unscoped())
}

func (p pANTRYITEMUNITDo) Create(values ...*model.PANTRYITEMUNIT) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p pANTRYITEMUNITDo) CreateInBatches(values []*model.PANTRYITEMUNIT, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p pANTRYITEMUNITDo) Save(values ...*model.PANTRYITEMUNIT) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p pANTRYITEMUNITDo) First() (*model.PANTRYITEMUNIT, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PANTRYITEMUNIT), nil
	}
}

func (p pANTRYITEMUNITDo) Take() (*model.PANTRYITEMUNIT, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PANTRYITEMUNIT), nil
	}
}

func (p pANTRYITEMUNITDo) Last() (*model.PANTRYITEMUNIT, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PANTRYITEMUNIT), nil
	}
}

func (p pANTRYITEMUNITDo) Find() ([]*model.PANTRYITEMUNIT, error) {
	result, err := p.DO.Find()
	return result.([]*model.PANTRYITEMUNIT), err
}

func (p pANTRYITEMUNITDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PANTRYITEMUNIT, err error) {
	buf := make([]*model.PANTRYITEMUNIT, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p pANTRYITEMUNITDo) FindInBatches(result *[]*model.PANTRYITEMUNIT, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p pANTRYITEMUNITDo) Attrs(attrs ...field.AssignExpr) *pANTRYITEMUNITDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p pANTRYITEMUNITDo) Assign(attrs ...field.AssignExpr) *pANTRYITEMUNITDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p pANTRYITEMUNITDo) Joins(fields ...field.RelationField) *pANTRYITEMUNITDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p pANTRYITEMUNITDo) Preload(fields ...field.RelationField) *pANTRYITEMUNITDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p pANTRYITEMUNITDo) FirstOrInit() (*model.PANTRYITEMUNIT, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PANTRYITEMUNIT), nil
	}
}

func (p pANTRYITEMUNITDo) FirstOrCreate() (*model.PANTRYITEMUNIT, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PANTRYITEMUNIT), nil
	}
}

func (p pANTRYITEMUNITDo) FindByPage(offset int, limit int) (result []*model.PANTRYITEMUNIT, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p pANTRYITEMUNITDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p pANTRYITEMUNITDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p pANTRYITEMUNITDo) Delete(models ...*model.PANTRYITEMUNIT) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *pANTRYITEMUNITDo) withDO(do gen.Dao) *pANTRYITEMUNITDo {
	p.DO = *do.(*gen.DO)
	return p
}
