// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"SMART_OFFICE_APP/pkg/db/model"
)

func newPANTRYROOMPANTRYMAPPING(db *gorm.DB, opts ...gen.DOOption) pANTRYROOMPANTRYMAPPING {
	_pANTRYROOMPANTRYMAPPING := pANTRYROOMPANTRYMAPPING{}

	_pANTRYROOMPANTRYMAPPING.pANTRYROOMPANTRYMAPPINGDo.UseDB(db, opts...)
	_pANTRYROOMPANTRYMAPPING.pANTRYROOMPANTRYMAPPINGDo.UseModel(&model.PANTRYROOMPANTRYMAPPING{})

	tableName := _pANTRYROOMPANTRYMAPPING.pANTRYROOMPANTRYMAPPINGDo.TableName()
	_pANTRYROOMPANTRYMAPPING.ALL = field.NewAsterisk(tableName)
	_pANTRYROOMPANTRYMAPPING.PANTRYID = field.NewInt64(tableName, "PANTRY_ID")
	_pANTRYROOMPANTRYMAPPING.ROOMSID = field.NewInt64(tableName, "ROOMS_ID")
	_pANTRYROOMPANTRYMAPPING.ISACTIVE = field.NewBool(tableName, "IS_ACTIVE")

	_pANTRYROOMPANTRYMAPPING.fillFieldMap()

	return _pANTRYROOMPANTRYMAPPING
}

type pANTRYROOMPANTRYMAPPING struct {
	pANTRYROOMPANTRYMAPPINGDo

	ALL      field.Asterisk
	PANTRYID field.Int64
	ROOMSID  field.Int64
	ISACTIVE field.Bool

	fieldMap map[string]field.Expr
}

func (p pANTRYROOMPANTRYMAPPING) Table(newTableName string) *pANTRYROOMPANTRYMAPPING {
	p.pANTRYROOMPANTRYMAPPINGDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p pANTRYROOMPANTRYMAPPING) As(alias string) *pANTRYROOMPANTRYMAPPING {
	p.pANTRYROOMPANTRYMAPPINGDo.DO = *(p.pANTRYROOMPANTRYMAPPINGDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *pANTRYROOMPANTRYMAPPING) updateTableName(table string) *pANTRYROOMPANTRYMAPPING {
	p.ALL = field.NewAsterisk(table)
	p.PANTRYID = field.NewInt64(table, "PANTRY_ID")
	p.ROOMSID = field.NewInt64(table, "ROOMS_ID")
	p.ISACTIVE = field.NewBool(table, "IS_ACTIVE")

	p.fillFieldMap()

	return p
}

func (p *pANTRYROOMPANTRYMAPPING) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *pANTRYROOMPANTRYMAPPING) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 3)
	p.fieldMap["PANTRY_ID"] = p.PANTRYID
	p.fieldMap["ROOMS_ID"] = p.ROOMSID
	p.fieldMap["IS_ACTIVE"] = p.ISACTIVE
}

func (p pANTRYROOMPANTRYMAPPING) clone(db *gorm.DB) pANTRYROOMPANTRYMAPPING {
	p.pANTRYROOMPANTRYMAPPINGDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p pANTRYROOMPANTRYMAPPING) replaceDB(db *gorm.DB) pANTRYROOMPANTRYMAPPING {
	p.pANTRYROOMPANTRYMAPPINGDo.ReplaceDB(db)
	return p
}

type pANTRYROOMPANTRYMAPPINGDo struct{ gen.DO }

func (p pANTRYROOMPANTRYMAPPINGDo) Debug() *pANTRYROOMPANTRYMAPPINGDo {
	return p.withDO(p.DO.Debug())
}

func (p pANTRYROOMPANTRYMAPPINGDo) WithContext(ctx context.Context) *pANTRYROOMPANTRYMAPPINGDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p pANTRYROOMPANTRYMAPPINGDo) ReadDB() *pANTRYROOMPANTRYMAPPINGDo {
	return p.Clauses(dbresolver.Read)
}

func (p pANTRYROOMPANTRYMAPPINGDo) WriteDB() *pANTRYROOMPANTRYMAPPINGDo {
	return p.Clauses(dbresolver.Write)
}

func (p pANTRYROOMPANTRYMAPPINGDo) Session(config *gorm.Session) *pANTRYROOMPANTRYMAPPINGDo {
	return p.withDO(p.DO.Session(config))
}

func (p pANTRYROOMPANTRYMAPPINGDo) Clauses(conds ...clause.Expression) *pANTRYROOMPANTRYMAPPINGDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p pANTRYROOMPANTRYMAPPINGDo) Returning(value interface{}, columns ...string) *pANTRYROOMPANTRYMAPPINGDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p pANTRYROOMPANTRYMAPPINGDo) Not(conds ...gen.Condition) *pANTRYROOMPANTRYMAPPINGDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p pANTRYROOMPANTRYMAPPINGDo) Or(conds ...gen.Condition) *pANTRYROOMPANTRYMAPPINGDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p pANTRYROOMPANTRYMAPPINGDo) Select(conds ...field.Expr) *pANTRYROOMPANTRYMAPPINGDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p pANTRYROOMPANTRYMAPPINGDo) Where(conds ...gen.Condition) *pANTRYROOMPANTRYMAPPINGDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p pANTRYROOMPANTRYMAPPINGDo) Order(conds ...field.Expr) *pANTRYROOMPANTRYMAPPINGDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p pANTRYROOMPANTRYMAPPINGDo) Distinct(cols ...field.Expr) *pANTRYROOMPANTRYMAPPINGDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p pANTRYROOMPANTRYMAPPINGDo) Omit(cols ...field.Expr) *pANTRYROOMPANTRYMAPPINGDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p pANTRYROOMPANTRYMAPPINGDo) Join(table schema.Tabler, on ...field.Expr) *pANTRYROOMPANTRYMAPPINGDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p pANTRYROOMPANTRYMAPPINGDo) LeftJoin(table schema.Tabler, on ...field.Expr) *pANTRYROOMPANTRYMAPPINGDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p pANTRYROOMPANTRYMAPPINGDo) RightJoin(table schema.Tabler, on ...field.Expr) *pANTRYROOMPANTRYMAPPINGDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p pANTRYROOMPANTRYMAPPINGDo) Group(cols ...field.Expr) *pANTRYROOMPANTRYMAPPINGDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p pANTRYROOMPANTRYMAPPINGDo) Having(conds ...gen.Condition) *pANTRYROOMPANTRYMAPPINGDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p pANTRYROOMPANTRYMAPPINGDo) Limit(limit int) *pANTRYROOMPANTRYMAPPINGDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p pANTRYROOMPANTRYMAPPINGDo) Offset(offset int) *pANTRYROOMPANTRYMAPPINGDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p pANTRYROOMPANTRYMAPPINGDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *pANTRYROOMPANTRYMAPPINGDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p pANTRYROOMPANTRYMAPPINGDo) Unscoped() *pANTRYROOMPANTRYMAPPINGDo {
	return p.withDO(p.DO.Unscoped())
}

func (p pANTRYROOMPANTRYMAPPINGDo) Create(values ...*model.PANTRYROOMPANTRYMAPPING) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p pANTRYROOMPANTRYMAPPINGDo) CreateInBatches(values []*model.PANTRYROOMPANTRYMAPPING, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p pANTRYROOMPANTRYMAPPINGDo) Save(values ...*model.PANTRYROOMPANTRYMAPPING) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p pANTRYROOMPANTRYMAPPINGDo) First() (*model.PANTRYROOMPANTRYMAPPING, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PANTRYROOMPANTRYMAPPING), nil
	}
}

func (p pANTRYROOMPANTRYMAPPINGDo) Take() (*model.PANTRYROOMPANTRYMAPPING, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PANTRYROOMPANTRYMAPPING), nil
	}
}

func (p pANTRYROOMPANTRYMAPPINGDo) Last() (*model.PANTRYROOMPANTRYMAPPING, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PANTRYROOMPANTRYMAPPING), nil
	}
}

func (p pANTRYROOMPANTRYMAPPINGDo) Find() ([]*model.PANTRYROOMPANTRYMAPPING, error) {
	result, err := p.DO.Find()
	return result.([]*model.PANTRYROOMPANTRYMAPPING), err
}

func (p pANTRYROOMPANTRYMAPPINGDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PANTRYROOMPANTRYMAPPING, err error) {
	buf := make([]*model.PANTRYROOMPANTRYMAPPING, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p pANTRYROOMPANTRYMAPPINGDo) FindInBatches(result *[]*model.PANTRYROOMPANTRYMAPPING, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p pANTRYROOMPANTRYMAPPINGDo) Attrs(attrs ...field.AssignExpr) *pANTRYROOMPANTRYMAPPINGDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p pANTRYROOMPANTRYMAPPINGDo) Assign(attrs ...field.AssignExpr) *pANTRYROOMPANTRYMAPPINGDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p pANTRYROOMPANTRYMAPPINGDo) Joins(fields ...field.RelationField) *pANTRYROOMPANTRYMAPPINGDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p pANTRYROOMPANTRYMAPPINGDo) Preload(fields ...field.RelationField) *pANTRYROOMPANTRYMAPPINGDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p pANTRYROOMPANTRYMAPPINGDo) FirstOrInit() (*model.PANTRYROOMPANTRYMAPPING, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PANTRYROOMPANTRYMAPPING), nil
	}
}

func (p pANTRYROOMPANTRYMAPPINGDo) FirstOrCreate() (*model.PANTRYROOMPANTRYMAPPING, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PANTRYROOMPANTRYMAPPING), nil
	}
}

func (p pANTRYROOMPANTRYMAPPINGDo) FindByPage(offset int, limit int) (result []*model.PANTRYROOMPANTRYMAPPING, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p pANTRYROOMPANTRYMAPPINGDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p pANTRYROOMPANTRYMAPPINGDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p pANTRYROOMPANTRYMAPPINGDo) Delete(models ...*model.PANTRYROOMPANTRYMAPPING) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *pANTRYROOMPANTRYMAPPINGDo) withDO(do gen.Dao) *pANTRYROOMPANTRYMAPPINGDo {
	p.DO = *do.(*gen.DO)
	return p
}
