// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"SMART_OFFICE_APP/pkg/db/model"
)

func newPANTRYITEMSMAP(db *gorm.DB, opts ...gen.DOOption) pANTRYITEMSMAP {
	_pANTRYITEMSMAP := pANTRYITEMSMAP{}

	_pANTRYITEMSMAP.pANTRYITEMSMAPDo.UseDB(db, opts...)
	_pANTRYITEMSMAP.pANTRYITEMSMAPDo.UseModel(&model.PANTRYITEMSMAP{})

	tableName := _pANTRYITEMSMAP.pANTRYITEMSMAPDo.TableName()
	_pANTRYITEMSMAP.ALL = field.NewAsterisk(tableName)
	_pANTRYITEMSMAP.PANTRYID = field.NewInt64(tableName, "PANTRY_ID")
	_pANTRYITEMSMAP.ITEMID = field.NewInt64(tableName, "ITEM_ID")

	_pANTRYITEMSMAP.fillFieldMap()

	return _pANTRYITEMSMAP
}

type pANTRYITEMSMAP struct {
	pANTRYITEMSMAPDo

	ALL      field.Asterisk
	PANTRYID field.Int64
	ITEMID   field.Int64

	fieldMap map[string]field.Expr
}

func (p pANTRYITEMSMAP) Table(newTableName string) *pANTRYITEMSMAP {
	p.pANTRYITEMSMAPDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p pANTRYITEMSMAP) As(alias string) *pANTRYITEMSMAP {
	p.pANTRYITEMSMAPDo.DO = *(p.pANTRYITEMSMAPDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *pANTRYITEMSMAP) updateTableName(table string) *pANTRYITEMSMAP {
	p.ALL = field.NewAsterisk(table)
	p.PANTRYID = field.NewInt64(table, "PANTRY_ID")
	p.ITEMID = field.NewInt64(table, "ITEM_ID")

	p.fillFieldMap()

	return p
}

func (p *pANTRYITEMSMAP) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *pANTRYITEMSMAP) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 2)
	p.fieldMap["PANTRY_ID"] = p.PANTRYID
	p.fieldMap["ITEM_ID"] = p.ITEMID
}

func (p pANTRYITEMSMAP) clone(db *gorm.DB) pANTRYITEMSMAP {
	p.pANTRYITEMSMAPDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p pANTRYITEMSMAP) replaceDB(db *gorm.DB) pANTRYITEMSMAP {
	p.pANTRYITEMSMAPDo.ReplaceDB(db)
	return p
}

type pANTRYITEMSMAPDo struct{ gen.DO }

func (p pANTRYITEMSMAPDo) Debug() *pANTRYITEMSMAPDo {
	return p.withDO(p.DO.Debug())
}

func (p pANTRYITEMSMAPDo) WithContext(ctx context.Context) *pANTRYITEMSMAPDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p pANTRYITEMSMAPDo) ReadDB() *pANTRYITEMSMAPDo {
	return p.Clauses(dbresolver.Read)
}

func (p pANTRYITEMSMAPDo) WriteDB() *pANTRYITEMSMAPDo {
	return p.Clauses(dbresolver.Write)
}

func (p pANTRYITEMSMAPDo) Session(config *gorm.Session) *pANTRYITEMSMAPDo {
	return p.withDO(p.DO.Session(config))
}

func (p pANTRYITEMSMAPDo) Clauses(conds ...clause.Expression) *pANTRYITEMSMAPDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p pANTRYITEMSMAPDo) Returning(value interface{}, columns ...string) *pANTRYITEMSMAPDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p pANTRYITEMSMAPDo) Not(conds ...gen.Condition) *pANTRYITEMSMAPDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p pANTRYITEMSMAPDo) Or(conds ...gen.Condition) *pANTRYITEMSMAPDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p pANTRYITEMSMAPDo) Select(conds ...field.Expr) *pANTRYITEMSMAPDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p pANTRYITEMSMAPDo) Where(conds ...gen.Condition) *pANTRYITEMSMAPDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p pANTRYITEMSMAPDo) Order(conds ...field.Expr) *pANTRYITEMSMAPDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p pANTRYITEMSMAPDo) Distinct(cols ...field.Expr) *pANTRYITEMSMAPDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p pANTRYITEMSMAPDo) Omit(cols ...field.Expr) *pANTRYITEMSMAPDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p pANTRYITEMSMAPDo) Join(table schema.Tabler, on ...field.Expr) *pANTRYITEMSMAPDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p pANTRYITEMSMAPDo) LeftJoin(table schema.Tabler, on ...field.Expr) *pANTRYITEMSMAPDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p pANTRYITEMSMAPDo) RightJoin(table schema.Tabler, on ...field.Expr) *pANTRYITEMSMAPDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p pANTRYITEMSMAPDo) Group(cols ...field.Expr) *pANTRYITEMSMAPDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p pANTRYITEMSMAPDo) Having(conds ...gen.Condition) *pANTRYITEMSMAPDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p pANTRYITEMSMAPDo) Limit(limit int) *pANTRYITEMSMAPDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p pANTRYITEMSMAPDo) Offset(offset int) *pANTRYITEMSMAPDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p pANTRYITEMSMAPDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *pANTRYITEMSMAPDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p pANTRYITEMSMAPDo) Unscoped() *pANTRYITEMSMAPDo {
	return p.withDO(p.DO.Unscoped())
}

func (p pANTRYITEMSMAPDo) Create(values ...*model.PANTRYITEMSMAP) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p pANTRYITEMSMAPDo) CreateInBatches(values []*model.PANTRYITEMSMAP, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p pANTRYITEMSMAPDo) Save(values ...*model.PANTRYITEMSMAP) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p pANTRYITEMSMAPDo) First() (*model.PANTRYITEMSMAP, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PANTRYITEMSMAP), nil
	}
}

func (p pANTRYITEMSMAPDo) Take() (*model.PANTRYITEMSMAP, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PANTRYITEMSMAP), nil
	}
}

func (p pANTRYITEMSMAPDo) Last() (*model.PANTRYITEMSMAP, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PANTRYITEMSMAP), nil
	}
}

func (p pANTRYITEMSMAPDo) Find() ([]*model.PANTRYITEMSMAP, error) {
	result, err := p.DO.Find()
	return result.([]*model.PANTRYITEMSMAP), err
}

func (p pANTRYITEMSMAPDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PANTRYITEMSMAP, err error) {
	buf := make([]*model.PANTRYITEMSMAP, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p pANTRYITEMSMAPDo) FindInBatches(result *[]*model.PANTRYITEMSMAP, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p pANTRYITEMSMAPDo) Attrs(attrs ...field.AssignExpr) *pANTRYITEMSMAPDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p pANTRYITEMSMAPDo) Assign(attrs ...field.AssignExpr) *pANTRYITEMSMAPDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p pANTRYITEMSMAPDo) Joins(fields ...field.RelationField) *pANTRYITEMSMAPDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p pANTRYITEMSMAPDo) Preload(fields ...field.RelationField) *pANTRYITEMSMAPDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p pANTRYITEMSMAPDo) FirstOrInit() (*model.PANTRYITEMSMAP, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PANTRYITEMSMAP), nil
	}
}

func (p pANTRYITEMSMAPDo) FirstOrCreate() (*model.PANTRYITEMSMAP, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PANTRYITEMSMAP), nil
	}
}

func (p pANTRYITEMSMAPDo) FindByPage(offset int, limit int) (result []*model.PANTRYITEMSMAP, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p pANTRYITEMSMAPDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p pANTRYITEMSMAPDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p pANTRYITEMSMAPDo) Delete(models ...*model.PANTRYITEMSMAP) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *pANTRYITEMSMAPDo) withDO(do gen.Dao) *pANTRYITEMSMAPDo {
	p.DO = *do.(*gen.DO)
	return p
}
