// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"SMART_OFFICE_APP/pkg/db/model"
)

func newVMSROOMAMENITIESMAP(db *gorm.DB, opts ...gen.DOOption) vMSROOMAMENITIESMAP {
	_vMSROOMAMENITIESMAP := vMSROOMAMENITIESMAP{}

	_vMSROOMAMENITIESMAP.vMSROOMAMENITIESMAPDo.UseDB(db, opts...)
	_vMSROOMAMENITIESMAP.vMSROOMAMENITIESMAPDo.UseModel(&model.VMSROOMAMENITIESMAP{})

	tableName := _vMSROOMAMENITIESMAP.vMSROOMAMENITIESMAPDo.TableName()
	_vMSROOMAMENITIESMAP.ALL = field.NewAsterisk(tableName)
	_vMSROOMAMENITIESMAP.ROOMID = field.NewInt64(tableName, "ROOM_ID")
	_vMSROOMAMENITIESMAP.AMENITIESID = field.NewInt64(tableName, "AMENITIES_ID")

	_vMSROOMAMENITIESMAP.fillFieldMap()

	return _vMSROOMAMENITIESMAP
}

type vMSROOMAMENITIESMAP struct {
	vMSROOMAMENITIESMAPDo

	ALL         field.Asterisk
	ROOMID      field.Int64
	AMENITIESID field.Int64

	fieldMap map[string]field.Expr
}

func (v vMSROOMAMENITIESMAP) Table(newTableName string) *vMSROOMAMENITIESMAP {
	v.vMSROOMAMENITIESMAPDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v vMSROOMAMENITIESMAP) As(alias string) *vMSROOMAMENITIESMAP {
	v.vMSROOMAMENITIESMAPDo.DO = *(v.vMSROOMAMENITIESMAPDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *vMSROOMAMENITIESMAP) updateTableName(table string) *vMSROOMAMENITIESMAP {
	v.ALL = field.NewAsterisk(table)
	v.ROOMID = field.NewInt64(table, "ROOM_ID")
	v.AMENITIESID = field.NewInt64(table, "AMENITIES_ID")

	v.fillFieldMap()

	return v
}

func (v *vMSROOMAMENITIESMAP) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *vMSROOMAMENITIESMAP) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 2)
	v.fieldMap["ROOM_ID"] = v.ROOMID
	v.fieldMap["AMENITIES_ID"] = v.AMENITIESID
}

func (v vMSROOMAMENITIESMAP) clone(db *gorm.DB) vMSROOMAMENITIESMAP {
	v.vMSROOMAMENITIESMAPDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v vMSROOMAMENITIESMAP) replaceDB(db *gorm.DB) vMSROOMAMENITIESMAP {
	v.vMSROOMAMENITIESMAPDo.ReplaceDB(db)
	return v
}

type vMSROOMAMENITIESMAPDo struct{ gen.DO }

func (v vMSROOMAMENITIESMAPDo) Debug() *vMSROOMAMENITIESMAPDo {
	return v.withDO(v.DO.Debug())
}

func (v vMSROOMAMENITIESMAPDo) WithContext(ctx context.Context) *vMSROOMAMENITIESMAPDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v vMSROOMAMENITIESMAPDo) ReadDB() *vMSROOMAMENITIESMAPDo {
	return v.Clauses(dbresolver.Read)
}

func (v vMSROOMAMENITIESMAPDo) WriteDB() *vMSROOMAMENITIESMAPDo {
	return v.Clauses(dbresolver.Write)
}

func (v vMSROOMAMENITIESMAPDo) Session(config *gorm.Session) *vMSROOMAMENITIESMAPDo {
	return v.withDO(v.DO.Session(config))
}

func (v vMSROOMAMENITIESMAPDo) Clauses(conds ...clause.Expression) *vMSROOMAMENITIESMAPDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v vMSROOMAMENITIESMAPDo) Returning(value interface{}, columns ...string) *vMSROOMAMENITIESMAPDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v vMSROOMAMENITIESMAPDo) Not(conds ...gen.Condition) *vMSROOMAMENITIESMAPDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v vMSROOMAMENITIESMAPDo) Or(conds ...gen.Condition) *vMSROOMAMENITIESMAPDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v vMSROOMAMENITIESMAPDo) Select(conds ...field.Expr) *vMSROOMAMENITIESMAPDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v vMSROOMAMENITIESMAPDo) Where(conds ...gen.Condition) *vMSROOMAMENITIESMAPDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v vMSROOMAMENITIESMAPDo) Order(conds ...field.Expr) *vMSROOMAMENITIESMAPDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v vMSROOMAMENITIESMAPDo) Distinct(cols ...field.Expr) *vMSROOMAMENITIESMAPDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v vMSROOMAMENITIESMAPDo) Omit(cols ...field.Expr) *vMSROOMAMENITIESMAPDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v vMSROOMAMENITIESMAPDo) Join(table schema.Tabler, on ...field.Expr) *vMSROOMAMENITIESMAPDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v vMSROOMAMENITIESMAPDo) LeftJoin(table schema.Tabler, on ...field.Expr) *vMSROOMAMENITIESMAPDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v vMSROOMAMENITIESMAPDo) RightJoin(table schema.Tabler, on ...field.Expr) *vMSROOMAMENITIESMAPDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v vMSROOMAMENITIESMAPDo) Group(cols ...field.Expr) *vMSROOMAMENITIESMAPDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v vMSROOMAMENITIESMAPDo) Having(conds ...gen.Condition) *vMSROOMAMENITIESMAPDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v vMSROOMAMENITIESMAPDo) Limit(limit int) *vMSROOMAMENITIESMAPDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v vMSROOMAMENITIESMAPDo) Offset(offset int) *vMSROOMAMENITIESMAPDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v vMSROOMAMENITIESMAPDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *vMSROOMAMENITIESMAPDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v vMSROOMAMENITIESMAPDo) Unscoped() *vMSROOMAMENITIESMAPDo {
	return v.withDO(v.DO.Unscoped())
}

func (v vMSROOMAMENITIESMAPDo) Create(values ...*model.VMSROOMAMENITIESMAP) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v vMSROOMAMENITIESMAPDo) CreateInBatches(values []*model.VMSROOMAMENITIESMAP, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v vMSROOMAMENITIESMAPDo) Save(values ...*model.VMSROOMAMENITIESMAP) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v vMSROOMAMENITIESMAPDo) First() (*model.VMSROOMAMENITIESMAP, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.VMSROOMAMENITIESMAP), nil
	}
}

func (v vMSROOMAMENITIESMAPDo) Take() (*model.VMSROOMAMENITIESMAP, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.VMSROOMAMENITIESMAP), nil
	}
}

func (v vMSROOMAMENITIESMAPDo) Last() (*model.VMSROOMAMENITIESMAP, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.VMSROOMAMENITIESMAP), nil
	}
}

func (v vMSROOMAMENITIESMAPDo) Find() ([]*model.VMSROOMAMENITIESMAP, error) {
	result, err := v.DO.Find()
	return result.([]*model.VMSROOMAMENITIESMAP), err
}

func (v vMSROOMAMENITIESMAPDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.VMSROOMAMENITIESMAP, err error) {
	buf := make([]*model.VMSROOMAMENITIESMAP, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v vMSROOMAMENITIESMAPDo) FindInBatches(result *[]*model.VMSROOMAMENITIESMAP, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v vMSROOMAMENITIESMAPDo) Attrs(attrs ...field.AssignExpr) *vMSROOMAMENITIESMAPDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v vMSROOMAMENITIESMAPDo) Assign(attrs ...field.AssignExpr) *vMSROOMAMENITIESMAPDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v vMSROOMAMENITIESMAPDo) Joins(fields ...field.RelationField) *vMSROOMAMENITIESMAPDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v vMSROOMAMENITIESMAPDo) Preload(fields ...field.RelationField) *vMSROOMAMENITIESMAPDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v vMSROOMAMENITIESMAPDo) FirstOrInit() (*model.VMSROOMAMENITIESMAP, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.VMSROOMAMENITIESMAP), nil
	}
}

func (v vMSROOMAMENITIESMAPDo) FirstOrCreate() (*model.VMSROOMAMENITIESMAP, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.VMSROOMAMENITIESMAP), nil
	}
}

func (v vMSROOMAMENITIESMAPDo) FindByPage(offset int, limit int) (result []*model.VMSROOMAMENITIESMAP, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v vMSROOMAMENITIESMAPDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v vMSROOMAMENITIESMAPDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v vMSROOMAMENITIESMAPDo) Delete(models ...*model.VMSROOMAMENITIESMAP) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *vMSROOMAMENITIESMAPDo) withDO(do gen.Dao) *vMSROOMAMENITIESMAPDo {
	v.DO = *do.(*gen.DO)
	return v
}
